var allColors = [
    "Light Golden Rod Yellow",
    "Dark Golden Rod",
    "Dark Olive Green",
    "Dark Sea Green",
    "Dark Slate Blue",
    "Dark Slate Gray",
    "Dark Slate Grey",
    "Deep Sky Blue",
    "Light Sea Green",
    "Light Sky Blue",
    "Light Slate Gray",
    "Light Slate Grey",
    "Light Steel Blue",
    "Medium Aqua Marine",
    "Medium Sea Green",
    "Medium Slate Blue",
    "Medium Spring Green",
    "Medium Violet Red",
    "Pale Golden Rod",
    "Pale Violet Red",
    "Orange Red",
    "Hot Pink",
    "Rebecca Purple",
    "Alice Blue",
    "Antique White",
    "Blanched Almond",
    "Blue Violet",
    "Burly Wood",
    "Cadet Blue",
    "Cornflower Blue",
    "Dark Blue",
    "Dark Cyan",
    "Dark Gray",
    "Dark Grey",
    "Dark Green",
    "Dark Khaki",
    "Dark Magenta",
    "Dark Orange",
    "Dark Orchid",
    "Dark Red",
    "Dark Salmon",
    "Dark Turquoise",
    "Dark Violet",
    "Deep Pink",
    "Dim Gray",
    "Dim Grey",
    "Dodger Blue",
    "Fire Brick",
    "Floral White",
    "Forest Green",
    "Ghost White",
    "Golden Rod",
    "Green Yellow",
    "Honey Dew",
    "Indian Red",
    "Lavender Blush",
    "Lawn Green",
    "Lemon Chiffon",
    "Light Blue",
    "Light Coral",
    "Light Cyan",
    "Light Gray",
    "Light Grey",
    "Light Green",
    "Light Pink",
    "Light Salmon",
    "Light Yellow",
    "Lime Green",
    "Medium Blue",
    "Medium Orchid",
    "Medium Purple",
    "Medium Turquoise",
    "Midnight Blue",
    "Mint Cream",
    "Misty Rose",
    "Navajo White",
    "Old Lace",
    "Olive Drab",
    "Pale Green",
    "Pale Turquoise",
    "Papaya Whip",
    "Peach Puff",
    "Powder Blue",
    "Rosy Brown",
    "Royal Blue",
    "Saddle Brown",
    "Sandy Brown",
    "Sea Green",
    "Sea Shell",
    "Sky Blue",
    "Slate Blue",
    "Slate Gray",
    "Slate Grey",
    "Spring Green",
    "Steel Blue",
    "White Smoke",
    "Yellow Green",
    "Azure",
    "Beige",
    "Blue",
    "Black",
    "Brown",
    "Chocolate",
    "Coral",
    "Cyan",
    "Gray",
    "Grey",
    "Green",
    "Gold",
    "Indigo",
    "Lime",
    "Magenta",
    "Maroon",
    "Olive",
    "Orange",
    "Pink",
    "Plum",
    "Purple",
    "Red",
    "Salmon",
    "Silver",
    "Snow",
    "Tomato",
    "Turquoise",
    "Violet",
    "Yellow",
    "White",
    "Aqua",
    "Aquamarine",
    "Bisque",
    "Chartreuse",
    "Cornsilk",
    "Crimson",
    "Fuchsia",
    "Gainsboro",
    "Ivory",
    "Khaki",
    "Lavender",
    "Linen",
    "Moccasin",
    "Navy",
    "Orchid",
    "Peru",
    "Sienna",
    "Tan",
    "Teal",
    "Thistle",
    "Wheat"
]